packageExtensions:
  bootstrap-vue@*:
    dependencies:
      jquery: "*"
      vue: ^2.7.14
  vue-demi@*:
    dependencies:
      vue: ^2.7.14
  vue-eslint-parser@*:
    dependencies:
      "@typescript-eslint/parser": "*"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
