packageExtensions:
  "bootstrap-vue@*":
    dependencies:
      "vue": "^2.7.10"
      "jquery": "*"
  "vue-demi@*":
    dependencies:
      "vue": "^2.7.10"
  "vue-eslint-parser@*":
    dependencies:
      "@typescript-eslint/parser" : "*"

yarnPath: ".yarn/releases/yarn-berry.cjs"
