packageExtensions:
  "bootstrap-vue@*":
    dependencies:
      "vue": "^2.6.14"
      "jquery": "*"
  "vue-demi@*":
    dependencies:
      "vue": "^2.6.14"
  "vue-eslint-parser@*":
    dependencies:
      "@typescript-eslint/parser" : "*"

